title: Centro Tecnologia Rocci
email: ""
description: >-
  Spazio personale dedicato allo sviluppo software, alla prototipazione elettronica,
  ai progetti maker e alle passioni outdoor (MTB, trekking e coltivazione).
baseurl: ""
url: "https://luca-rocci.github.io"

theme: minima

header_pages:
  - apps/index.md
  - tech/index.md
  - outdoor/index.md
  - chi-sono.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%d-%m-%Y"
  social_links:
    github: luca-rocci
    linkedin: lucarocci
